server:
  port: 9001

spring:
  application:
    name: shop-user-service
  #激活开发环境配置
  profiles:
    active: dev

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  #Redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0 # Redis数据库索引(默认为0)
      timeout: 3000ms # 连接超时时间
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数(使用负值表示没有限制)
          max-idle: 8 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
          max-wait: -1ms # 连接池最大阻塞等待时间(使用负值表示没有限制)
        shutdown-timeout: 100ms # 关闭超时时间


#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: fun.timu.shop.user.model.DO
  # 全局配置
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名
      logic-delete-value: 1        # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0    # 逻辑未删除值(默认为 0)


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO

# 应用配置
app:
  # Snowflake ID生成器配置
  snowflake:
    # 机器ID (0-1023)，不同的服务实例需要配置不同的机器ID
    # 如果不配置，将自动根据IP地址生成
    machine-id: 1