server:
  port: 9003

spring:
  application:
    name: shop-product-service
  #激活开发环境配置
  profiles:
    active: dev

  # Nacos 配置导入
  config:
    import:
      - optional:nacos:shop-product-service.yaml
      - optional:nacos:common-config.yaml

  # Nacos 配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos服务器地址
        namespace: a734a22d-e648-44ce-9208-00d3be552318
        group: DEFAULT_GROUP # 服务分组
      config:
        server-addr: localhost:8848 # Nacos配置中心地址
        file-extension: yaml # 配置文件格式
        namespace: a734a22d-e648-44ce-9208-00d3be552318
        group: DEFAULT_GROUP # 配置分组

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  #Redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0 # Redis数据库索引(默认为0)
      timeout: 3000ms # 连接超时时间
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数(使用负值表示没有限制)
          max-idle: 8 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
          max-wait: -1ms # 连接池最大阻塞等待时间(使用负值表示没有限制)
        shutdown-timeout: 100ms # 关闭超时时间

  #RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 发布确认
    publisher-confirm-type: correlated
    # 发布返回
    publisher-returns: true
    # 手动确认
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
        prefetch: 1


#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: fun.timu.shop.product.model.DO
  # 全局配置
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名
      logic-delete-value: 1        # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0    # 逻辑未删除值(默认为 0)


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO

# 应用配置
app:
  # Snowflake ID生成器配置
  snowflake:
    # 机器ID (0-1023)，不同的服务实例需要配置不同的机器ID
    # 如果不配置，将自动根据IP地址生成
    machine-id: 3

# 产品服务消息队列配置
mqconfig:
  # 产品相关配置
  product_event_exchange: product.event.exchange
  stock_locked_queue: stock.locked.queue
  stock_locked_routing_key: stock.locked.routing.key
  stock_release_queue: stock.release.queue
  stock_release_routing_key: stock.release.routing.key
  product_update_queue: product.update.queue
  product_update_routing_key: product.update.routing.key