server:
  port: 9000

spring:
  application:
    name: shop-gateway
  profiles:
    active: dev

  # Nacos 配置导入
  config:
    import:
      - optional:nacos:shop-gateway.yaml
      - optional:nacos:common-config.yaml

  # Nacos 配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos服务器地址
        namespace: a734a22d-e648-44ce-9208-00d3be552318
        group: DEFAULT_GROUP # 服务分组
      config:
        server-addr: localhost:8848 # Nacos配置中心地址
        file-extension: yaml # 配置文件格式
        namespace: a734a22d-e648-44ce-9208-00d3be552318
        group: DEFAULT_GROUP # 配置分组
    
    # Gateway 路由配置
    gateway:
      discovery:
        locator:
          enabled: true # 启用服务发现路由
          lower-case-service-id: true # 服务名小写
      routes:
        # 用户服务路由
        - id: shop-user-service
          uri: lb://shop-user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        
        # 商品服务路由
        - id: shop-product-service
          uri: lb://shop-product-service
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=2
            
        # 订单服务路由
        - id: shop-order-service
          uri: lb://shop-order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2
            
        # 优惠券服务路由
        - id: shop-coupon-service
          uri: lb://shop-coupon-service
          predicates:
            - Path=/api/coupon/**
          filters:
            - StripPrefix=2

#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: debug
    fun.timu.shop.gateway: debug

# 应用配置
app:
  # Snowflake ID生成器配置
  snowflake:
    # 机器ID (0-1023)，不同的服务实例需要配置不同的机器ID
    # 如果不配置，将自动根据IP地址生成
    machine-id: 0
